### ISSUE TITLE
pod search IMYAOPTableView [!]  -------- Unable to find a pod with name, author, summary, or descriptionmatching `IMYAOPTableView`

### ISSUE THREAD

**Issue by Jinxiansen** [li6185377/IMYAOPTableView#1]
pod search IMYAOPTableView
[!] Unable to find a pod with name, author, summary, or descriptionmatching `IMYAOPTableView`

**Comment by li6185377** [comment]
1周前才上传的，你可以先执行下： pod repo update  再搜索。
