### ISSUE TITLE
this class is not key value coding-compliant for the key _options

### ISSUE THREAD

**Issue by saberChen** [li6185377/IMYAOPTableView#10]
<IMYAOPTableViewUtils.m:(128)> [<NSKeyValueObservance 0x113fda750> valueForUndefinedKey:]: this class is not key value coding-compliant for the key _options.
(
	0   CoreFoundation                      0x00000001840ee37c <redacted> + 148
	1   libobjc.A.dylib                     0x0000000183334528 objc_exception_throw + 56
	2   CoreFoundation                      0x00000001840ee02c <redacted> + 0
	3   Foundation                          0x0000000184aa2434 <redacted> + 248
	4   Foundation                          0x00000001849e8e20 <redacted> + 264
	5   PocketCampus                        0x0000000101c9ccbc -[IMYAOPTableViewUtils bindingTableView:aopClass:] + 1084
	6   PocketCampus                        0x0000000101c9c860 -[IMYAOPTableViewUtils injectTableView] + 524
	7   PocketCampus                        0x0000000101ca094c -[UITableView(AOPTableViewUtils) aop_utils] + 292

        ...

	37  PocketCampus                        0x000000010070a6d4 main + 192
	38  libdyld.dylib                       0x0000000183ad056c <redacted> + 4

报这样的错，改怎么修改呢

**Comment by li6185377** [comment]
release 环境会吗?

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by li6185377** [comment]
目前只有Debug 环境中偶尔出现
