### ISSUE TITLE
UICollectionView自定义layout不支持动态插入

### ISSUE THREAD

**Issue by Bertterman** [li6185377/IMYAOPTableView#12]
```
XXXCollectionViewFlowLayout  * layout = [[XXXCollectionViewFlowLayout alloc]init];
_recommandCollectionView = [[MJDQFilmCollectionNode alloc]initWithFrame:self.view.bounds collectionViewLayout:layout];
```
在这种自定义`UICollectionViewFlowLayout`的情况下，使用动态插入的方法，会受自定义layout影响

**Comment by li6185377** [comment]
可以参考  `CHTCollectionViewWaterfallLayout` 的注入实现，可以自己建个 IMYAOPCollectionViewUtils  category，添加你自定义layout的回调方法

**Comment by Bertterman** [comment]
刚好发现这个CHTCollectionViewWaterfallLayout。正在研究中。谢谢了啊！！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 八八九九 <notifications@github.com&gt;
发送时间: 2019年11月1日 17:00
收件人: MeetYouDevs/IMYAOPTableView <IMYAOPTableView@noreply.github.com&gt;
抄送: 陈鑫 <810263540@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[MeetYouDevs/IMYAOPTableView] UICollectionView自定义layout不支持动态插入 (#12)




可以参考  CHTCollectionViewWaterfallLayout 的注入实现，可以自己建个 IMYAOPCollectionViewUtils  category，添加你自定义layout的回调方法
