### ISSUE TITLE
UITableView+IMYAOPTableView 方法实现 bug

### ISSUE THREAD

**Issue by luoshihui** [li6185377/IMYAOPTableView#13]
在 tableview 支持滑动编辑时, 滑动会触发
-[NSIndexPath countByEnumeratingWithState:objects:count:]: unrecognized selector  闪退

排查发现UITableView+IMYAOPTableView.m文件的一个方法交换实现有误
![image](https://user-images.githubusercontent.com/4970812/150831240-8cb1d938-9770-441b-9ea9-1a6a0cb4461c.png)

如图所示, 应该为

![image](https://user-images.githubusercontent.com/4970812/150831508-2c41adf2-ffaa-41ac-b0f5-5212427fec55.png)

**Comment by li6185377** [comment]
已合并😁
