### ISSUE TITLE
您好，请教一下走这一步代码的目的是什么

### ISSUE THREAD

**Issue by dvdong** [li6185377/IMYAOPTableView#15]
<img width="888" alt="image" src="https://user-images.githubusercontent.com/36857548/157409358-9dfb54c4-d27b-483a-9392-cfaf9ba7b626.png">

如图，红框里的这一步，我看到每一个aop_开头的方法都进行了这个方法，不太理解是为什么，烦请指教。
遇到一个问题，就是当我的数据源数量是10的时候，并且我想插入广告到第10个位置，走了这个方法之后indexPath的row会变成11，导致dequeueReusableCellWithIdentifier:forIndexPath: 会报错  ’request for rect at invalid index path‘。
谢谢！

**Comment by dvdong** [comment]
<img width="875" alt="image" src="https://user-images.githubusercontent.com/36857548/157632123-9f61ccee-6332-44c3-875c-0cc1bad32354.png">
<img width="714" alt="image" src="https://user-images.githubusercontent.com/36857548/157632215-8ce9f2bb-0804-4d88-bdeb-833860db476b.png">
补充：使用您的Demo尝试了一下，修改了一下数据源和插入位置，如果想插入到列表最后一个位置，同样会出现崩溃

**Comment by li6185377** [comment]
> 

因为内部要处理 是系统回调 还是 外部代码调用，  外部代码调用 要区分是 广告调用 还是业务方， 如果是业务方，需要转为系统使用的 indexPath
