### ISSUE TITLE
collectionView存在header的时候，如果插入在第0个位置就会崩溃啊

### ISSUE THREAD

**Issue by nattychao** [li6185377/IMYAOPTableView#19]
*** Assertion failure in -[IMYAOPCollectionViewUtils collectionView:viewForSupplementaryElementOfKind:atIndexPath:], IMYAOPCollectionViewUtils+DataSource.m:120

**Comment by li6185377** [comment]
这个是内部断言， 你返回的 header view 不是 `UICollectionReusableView` 类型

**Comment by nattychao** [comment]
自定义的header是UICollectionReusableView的子类啊

**Comment by li6185377** [comment]
你可以在对应 断言处 断点看下 IMYAOPCollectionViewUtils+DataSource.m:120。  如果还不行 看下 方便建个Demo 我试下

**Comment by nattychao** [comment]
bug复现，我写在YYFlowlayoutViewController这个页面里了
[IMYAOPTableViewBug.zip](https://github.com/user-attachments/files/17515301/IMYAOPTableViewBug.zip)

**Comment by li6185377** [comment]
![image](https://github.com/user-attachments/assets/13ede9d9-8256-4cfd-9ca7-24f243959348)

IMYAOPCollectionDemo 作为业务的 DataSource 本身就没有实现 header view 的返回。  目前 AOP 还不支持 Header View 的注入。

**Comment by nattychao** [comment]
我疑惑的是为啥不插在0位置就不会走断言
