### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by ZenonHuang** [li6185377/IMYAOPTableView#3]
首页感谢作者的分享。
刚好需要接入广告，想起曾经看到这个东东。
运行Demo没问题。

接入后，按照demo方式。写了一个HZAdAOP文件。
在tableView所在控制器的 viewDidLoad 方法里，写入如下代码
```
//begin 插入代码
    self.aopDemo = [HZAdAOP new];
    self.aopDemo.aopUtils = self.tableView.aop_utils;
 //end
```
但是报错，全局断点在 `IMYAOPTableViewUtils.m`文件里的`bindingTableView: aopClass:`方法的代码:
```
 NSKeyValueObservingOptions options = [[observance valueForKey:@"_options"] unsignedIntegerValue];
```

错误输出：
```
[<NSKeyValueObservance 0x60800025eb40> valueForUndefinedKey:]: this class is not key value coding-compliant for the key _options.(null)
```

看我能怎么配合您？
实在不想强行写一个广告的cell进去，想用类似这样的aop方式

**Comment by li6185377** [comment]
可以写个 demo 给我

**Comment by ZenonHuang** [comment]
谢谢，到时候我贴地址上来

**Comment by ZenonHuang** [comment]
按最初在项目中的写法，是能使用的。

我猜测可能引入的第三方库，和您的文件冲突造成的。
之后加入了` MJRefresh.h`，成功复现了出来。劳烦您查看一下。

[Demo地址](https://github.com/zzgo/MyDemos/tree/master/AdCellDemo)

**Comment by li6185377** [comment]
很奇怪的问题，在 iOS10 中，相应的私有变量不见了，但是我自己应用却没事，我增加了 @try @catch，目前解决了，你可以执行下 pod update，目前版本 1.7.1

**Comment by ZenonHuang** [comment]
很棒棒，我把这个库推荐给其他朋友了。

可是不是pod更新的有问题呢？我现在更新到1.7.1还是一样的问题

**Comment by li6185377** [comment]
不会啊~ 我用你的 demo 是正常的
![image](https://cloud.githubusercontent.com/assets/1924211/21560208/5bb8e0fe-ce96-11e6-9fef-23c0e6a1d6c0.png)

**Comment by ZenonHuang** [comment]
OK,那应该是我的问题，我去清缓存，现在把issue关了
