### ISSUE TITLE
帮我看下图上的问题

### ISSUE THREAD

**Issue by MasterBetter** [li6185377/IMYAOPTableView#5]
![4821534842176_ pic](https://user-images.githubusercontent.com/13688441/44392134-160c0800-a564-11e8-926d-6d436cfc385a.jpg)
我是按照demo上操作的，集成之后出现了这个问题，不断的在原始图上添加新的。我这个tableview有2个区，我怎么在第二个区添加广告

**Comment by li6185377** [comment]
是说 设置 Section 吗？
![image](https://user-images.githubusercontent.com/1924211/44393619-c92a3080-a567-11e8-9981-f01dc5cf3c5b.png)

**Comment by MasterBetter** [comment]
我现在已经解决了 谢谢了
