### ISSUE TITLE
广告和列表非同一数据源,刷新广告崩溃

### ISSUE THREAD

**Issue by XGCoder** [li6185377/IMYAOPTableView#6]
按照示例代码进行插入广告后,在广告数据回来后刷新列表时崩溃. 

比如2.5.7.11 是广告位置,在列表数据回来时就计算好插入位置,同时去请求各个位置相对应的广告,刷新广告时在 `XXAOPTableDemo `类中` self.aopUtils.tableView `调用 `reloadRowsAtIndexPaths:withRowAnimation: `方法崩溃

**Comment by XGCoder** [comment]
崩溃日志 : 
` Exception=Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (38) must be equal to the number of rows contained in that section before the update (34), plus or minus the number of rows inserted or deleted from that section (1 inserted, 1 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).
Stack Trace:(
	0   CoreFoundation                      0x00000001833a6da4 <redacted> + 252
	1   libobjc.A.dylib                     0x00000001825605ec objc_exception_throw + 56
	2   CoreFoundation                      0x00000001833a6bf8 <redacted> + 0
	3   Foundation                          0x0000000183d96fa0 <redacted> + 112
	4   UIKit                               0x000000018d0de948 <redacted> + 14788
	5   UIKit                               0x000000018d0dadb8 <redacted> + 1068
	6   UIKit                               0x000000018d269b6c <redacted> + 148
	7   UIKit                               0x00000001a340604c <redacted> + 80
	8   weather                             0x00000001024d9a38 -[_IMYAOPTableView aop_reloadRowsAtIndexPaths:withRowAnimation:] + 404
	9   weather                             0x0000000102589ff0 __59-[WEAOPTableDemo getBayeAdaManager:adstyle_type:IndexPath:]_block_invoke + 1876
	10  weather                             0x000000010242dc24 -[WEBayeAdsManager nativeAdDidLoad:] + 1800
	11  weather                             0x0000000102a4a554 __24-[WMNativeAd loadAdData]_block_invoke + 368
	12  weather                             0x0000000102a345d4 __58-[WMAPIClient fetchNativeAdsWithAdSlot:completionHandler:]_block_invoke + 776
	13  weather                             0x0000000102a95000 __47-[WMNetworkAgent requestDidSucceedWithRequest:]_block_invoke + 96
	14  libdispatch.dylib                   0x00000001038051dc _dispatch_call_block_and_release + 24
	15  libdispatch.dylib                   0x000000010380519c _dispatch_client_callout + 16
	16  libdispatch.dylib                   0x0000000103809d2c _dispatch_main_queue_callback_4CF + 1180
	17  CoreFoundation                      0x000000018334f070 <redacted> + 12
	18  CoreFoundation                      0x000000018334cbc8 <redacted> + 2272
	19  CoreFoundation                      0x000000018326cda8 CFRunLoopRunSpecific + 552
	20  GraphicsServices                    0x0000000185252020 GSEventRunModal + 100
	21  UIKit                               0x000000018d28c758 UIApplicationMain + 236
	22  weather                             0x0000000102410908 main + 168
	23  libdyld.dylib                       0x0000000182cfdfc0 <redacted> + 4
)`

**Comment by li6185377** [comment]
你这个是数据源错乱了，有提前插入对应广告的 indexPath 吗？  
```
- (void)insertWithSections:(nullable NSArray<__kindof IMYAOPBaseInsertBody *> *)sections;
- (void)insertWithIndexPaths:(nullable NSArray<__kindof IMYAOPBaseInsertBody *> *)indexPaths;
```

**Comment by XGCoder** [comment]
抱歉 上周有事,没来得及回复  

插入了   我只有一组 就使用的 `- (void)insertWithIndexPaths:(nullable NSArray<__kindof IMYAOPBaseInsertBody *> *)indexPaths;`  方法, 我们新闻数据源每回的请求数据个数不一样,所以广告位以及广告信息都是获取到返回数据个数后才进行计算并且插入,同时进行请求  进而引发这样一个bug , 如果在刷新单独某个广告时再次插入的话 数据会不断循环刷新 ,插入 造成崩溃,

**Comment by XGCoder** [comment]
这个bug解决了 ,通过对数据源进行操作 每回进行校验 暂时处理了
