### ISSUE TITLE
使用的时候在业务中加入了aoputil，感觉不是完全无侵入

### ISSUE THREAD

**Issue by lichanghong** [li6185377/IMYAOPTableView#9]
使用的时候在业务中加入了aoputil，感觉不是完全无侵入，有没有完全无侵入方式？

**Comment by li6185377** [comment]
你可以在广告那层去 hook 业务相关的api，再使用 aoputils 就可以了

**Comment by lichanghong** [comment]
> 你可以在广告那层去 hook 业务相关的api，再使用 aoputils 就可以了

没想到回复那么及时！感谢
